kind: pipeline
type: docker      # 在 Docker 內部執行管道命令
name: kong-setup       # 可自行定義的名稱

steps:
  - name: tag-docker-image
    image: alpine
    commands:
    - echo -n "$(date +'%Y-%m-%d_%H-%M')_${DRONE_COMMIT}, latest" > .tags
  
  - name: build-docker-image
    image: plugins/docker
    settings:
      repo: libai.amastek.com.tw:8002/amas/kong-setup
      registry: libai.amastek.com.tw:8002
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      insecure: true
trigger: 
  event:
  - push
  - custom
  branch:
  - main